### ISSUE TITLE
Help for POST method

### ISSUE THREAD

**Issue by szetin** [nescalante/rodo#9]
Hi, I got strange issue, see below:

the implementation likes:

`fetch("localhost:8080/savedSearch",{
    method: "post",
    credentials: "include",
    headers: {"Content-Type": "application/json"},
    body: JSON.stringify({})
  });`

the test likes:
   `
   const request = mockServer.request().havingMethod("POST").havingPath('/savedSearch');
    return request.reply()
      .withHeader("content-type", "application/json")
      .withHeader("Access-Control-Allow-Origin", "*")
      .withStatus(200).withBody(responseBody);
`

but it doesn't work for me. When I delete ` credentials: "include",
    headers: {"Content-Type": "application/json"},` in the implementation, it works. Can someone tell me how to fix it?

**Comment by nescalante** [comment]
this worked for me:

```
const fetch = require('node-fetch');
const mockServer = require('rodo')(8080)

fetch('http://localhost:8080/savedSearch', { 
  method: 'post', 
  credentials: 'include', 
  headers: { 'Content-Type': 'application/json' }, 
  body: JSON.stringify({})
})
.then(response => {
  return response.json();
})
.then(json => {
  console.log(json);
});

const request = mockServer
  .request()
  .havingMethod('POST')
  .havingPath('/savedSearch'); 

return request
  .reply()
  .withHeader('content-type', 'application/json')
  .withHeader('Access-Control-Allow-Origin', '*')
  .withStatus(200)
  .withBody({ foo: 'bar' });
```
